version: '3'

services:
  nginx:
    image: nginx:1.21.4
    networks:
      - MyBridgeNetwork
    depends_on:
      - database

  database:
    image: mongo:4.2.2
    networks:
      - MyBridgeNetwork
    volumes:
      - /bdd

  geth:
    build: ./geth/
    networks:
      - BCNetwork
    volumes:
      - /blockchain


networks:
  MyBridgeNetwork:
    name: MyBridgeNetwork
    driver: bridge
    ipam: 
      config: 
        - subnet: 172.1.1.0/24

  BCNetwork:
    name: BCNetwork
    driver: bridge
    ipam: 
      config: 
        - subnet: 172.2.2.0/24